modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
[[mods]]
modId="battlemusic"
version="${file.jarVersion}"
displayName="Battle Music"
displayTest="IGNORE_ALL_VERSION"
logoFile="battlemusic.png"
credits="Minecraft Dungeons, Storymode, & Legends (Soundtrack)" #optional
authors="NekoTune" #optional
description='''
Adds fully configurable battle music

By default, gives music to elder guardians, wardens, the wither, and the ender dragon.
'''
[[dependencies.battlemusic]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.battlemusic]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.21)"
    ordering="NONE"
    side="CLIENT"