modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
[[mods]]
modId="battlemusic"
version="${file.jarVersion}"
displayName="Battle Music"
displayTest="IGNORE_ALL_VERSION"
logoFile="battlemusic.png"
credits="Minecraft Dungeons & Minecraft Storymode (Soundtrack)" #optional
authors="NekoTune" #optional
description='''
Adds battle music for strong monsters and bosses
'''
[[dependencies.battlemusic]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.battlemusic]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"