modLoader="javafml"
loaderVersion="[41,43]"
license="All rights reserved"
[[mods]]
modId="battlemusic"
version="1.0.1"
displayName="Battle Music"
displayTest="IGNORE_ALL_VERSION"
logoFile="battlemusic.png"
credits="Minecraft Dungeons, Storymode, & Legends (Soundtrack)" #optional
authors="NekoTune" #optional
description='''
Adds fully configurable battle music

By default, gives music to elder guardians, wardens, the wither, and the ender dragon.
'''
[[dependencies.battlemusic]]
    modId="forge"
    mandatory=true
    versionRange="[41,43]"
    ordering="NONE"
    side="BOTH"
[[dependencies.battlemusic]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.19.2]"
    ordering="NONE"
    side="CLIENT"